### ISSUE TITLE
code 255 still there in 4.3

### ISSUE THREAD

**Issue by martinjohansen98** [roothide/Bootstrap#151]
It says that it should be fixed in 4.3, but the issue persist for me, I still get error 255, any idea of what to do? I had it on 4.2, uninstalled and got beta 4.3 and nothing changed. Everything was working fine, but unfortunately I had a reboot and had to reapply bootstrap, as soon as that happened I started to get the error.

**Comment by roothide** [comment]
1: take a screenshot
2: try "bootstrap" then copy all logs and upload
3: zip /var/mobile/Library/Logs/CrashReporter and upload

**Comment by martinjohansen98** [comment]
ios-version: 16.6.1
device-model: iPhone11,6
app-version: 0.4.3
boot-session: 1DAD86EB-9D6F-4ECF-8783-3DCA5B15F14C
bootstrap installed
system not bootstrapped
bootstrap...

device is strapped: /var/containers/Bundle/Application/.jbroot-55C3231BB0E01FE1
Status: Rerandomize jbroot

Status: Building Base Binaries

Status: Starting Bootstrapd

bootstrap server load successful

bootstrap server check successful
Status: Updating Symlinks

Status: Rebuilding Apps

--Sileo.app--
--Zebra.app--
--/var/containers/Bundle/Application/01A2EE6D-90AC-4B7E-91F8-B3C4DB9E8C05/Snapchat.app--
--/var/containers/Bundle/Application/25492C77-4F41-4AEC-927C-5BAA127084F6/Filza.app--
--/var/containers/Bundle/Application/5181D012-BD14-4A93-B105-D2DD4773FEE6/Instagram.app--
--/var/containers/Bundle/Application/7C39C1FD-FADF-439F-92BE-7BC79CB48281/Volo.app--
--/var/containers/Bundle/Application/B5E12B29-C212-4316-9512-87C90F240382/Spotify.app--
--/var/containers/Bundle/Application/CF4321EA-1613-4AEF-8E13-EC5F667BB875/OPA.app--
--/var/containers/Bundle/Application/DE4541B4-553B-4BAE-928F-C4BAC70D7B36/YouTube.app--
Found 1 MachO slices.
File size 0x20aac bytes, MachO slice count 1.
Extracted Youtube best slice to /tmp/Qudcoc
Applying CoreTrust bypass...
Applying App Store code directory...
Adding new signature blob...
Updating TeamID...
TeamID set to T8ALTGMVXN!
Updating code slot hashes...
Encoding unsigned superblob...
Updating load commands...
Updating __LINKEDIT segment...
Updating LC_CODE
_SIGNATURE load command...
Updating code slot hashes...
Signing binary...
SHA256 hash: 78de75e558bf38ec8a1f863b7d1612193804aa94d08f344bede459080ddc5d77
Base64 hash: eN515Vi/OOyKH4Y7fRYSGTgEqpQ=
Encoding signed superblob...
Writing superblob to MachO...
Applied CoreTrust Bypass!
Found 1 MachO slices.
File size 0x1b20c bytes, MachO slice count 1.
Extracted OpenYoutube best slice to /tmp/2PJKL6
Applying CoreTrust bypass...
Applying App Store code directory...
Adding new signature blob...
Updating TeamID...
TeamID set to T8ALTGMVXN!
Updating code slot hashes...
Encoding unsigned superblob...
Updating load commands...
Updating __LINKEDIT segment...
Updating LC_CODE_SIGNATURE load command...
Updating code slot hashes...
Signing binary...
SHA256 hash: 55ea850bfbef784a51160f7d0cb7b89b17458bf74ca70b93d0e632f49a96d863
Base64 hash: VeqFC/vveEpRFg99DLe4mxdFi/c=
Encoding signed superblob...
Writing superblob to MachO...
Applied CoreTrust Bypass!
extracted failed /private/var/containers/Bundle/Application/DE4541B4-553B-4B
AE-928F-C4BAC70D7B36/YouTube.app/DontEatMyContent.bundle
Found 1 MachO slices.
File size 0x12930bc bytes, MachO slice count 1.

ERR:2024-01-17 16:37:08.993 uicache[5010:184399] freeplay: APPL:com.toyopagroup.picaboo
0,Undefined error: 0 : 5011 : /private/var/containers/Bundle/Application/01A2EE6D-90AC-4B7E-91F8-B3C4DB9E8C05/Snapchat.app/Snapchat
2024-01-17 16:37:10.111 uicache[5022:184508] freeplay: APPL:com.burbn.instagram
0,Undefined error: 0 : 5023 : /private/var/containers/Bundle/Application/5181D012-BD14-4A93-B105-D2DD4773FEE6/Instagram.app/Instagram
2024-01-17 16:37:10.720 uicache[5028:184539] freeplay: APPL:com.global.foodora.ios
0,Undefined error: 0 : 5030 : /private/var/containers/Bundle/Application/7C39C1FD-FADF-439F-92BE-7BC79CB48281/Volo.app/Volo
2024-01-17 16:37:11.034 uicache[5035:184563] freeplay: APPL:com.spotify.client
0,Undefined error: 0 : 5036 : /private/var/containers/Bundle/Application/B5E12B29-C212-4316-9512-87C90F240382/Spotify.app/Spotify
2024-01-17 16:37:11.699 uicache[5041:184583] 
freeplay: APPL:com.google.OPA
0,Undefined error: 0 : 5043 : /private/var/containers/Bundle/Application/CF4321EA-1613-4AEF-8E13-EC5F667BB875/OPA.app/OPA
2024-01-17 16:37:12.368 rebuildapp[5049:184615] [dumpEntitlements] no entitlements specified
Assertion failed: (realstore(bundleMainExecutablePath.UTF8String, entitlementsString.UTF8String, stripEntitlements.UTF8String) == 0), function signApp, file main.m, line 436.
Assertion failed: (execBinary(jbroot(argv[0]), argv) == 0), function registerPath, file main.m, line 567.

***exception: Bootstrap.m (367)

**Comment by martinjohansen98** [comment]
Crashreporter:
The crashreporter map was to big too upload here, even zipped, 270mb, uploaded to mega:
https://mega.nz/file/VSVUgQxR#k1qZDm0esyXBJbGUz000Yn6OSdYtxwUyUkdApUKXFBY

Screenshots:
![IMG_6469](https://github.com/roothide/Bootstrap/assets/15677422/0ef52b52-6765-4f1d-a511-6cfd4fbf0aa5)
![IMG_6470](https://github.com/roothide/Bootstrap/assets/15677422/897b4742-f3f3-40ad-9308-3a41398695ff)

**Comment by roothide** [comment]
could you zip /private/var/containers/Bundle/Application/DE4541B4-553B-4B
AE-928F-C4BAC70D7B36/YouTube.app/DontEatMyContent.bundle and upload?

**Comment by martinjohansen98** [comment]
[DontEatMyContent.zip](https://github.com/roothide/Bootstrap/files/13968169/DontEatMyContent.zip)

**Comment by roothide** [comment]
try the latest commits, should be fixed

**Comment by dayanch96** [comment]
> extracted failed /private/var/containers/Bundle/Application/DE4541B4-553B-4B
> AE-928F-C4BAC70D7B36/YouTube.app/DontEatMyContent.bundle

if issue still persist, try removing youtube app and bootstrap again
